### ISSUE TITLE
404 error when visiting API tools mentioned in the docs

### ISSUE THREAD

**Issue by mathewdblewis** [bybit-exchange/docs#55] opened 2020-05-06 01:34 UTC
The following four paths return a 404 error when visited:
/v2/private/order/create
/v2/private/order/cancel
/v2/private/order/cancelAll
/v2/private/stop-order/cancelAll

For example, if you go to this URL:
"https://api.bybit.com/v2/private/order/create"
you will get a 404 error using curl or firefox

The same also holds for all four of the paths given
above when using the test net, for example:
"https://api-testnet.bybit.com/v2/private/order/create"
also returns a 404 error

The four links are all given in these docs as valid API tools:
https://bybit-exchange.github.io/docs/inverse/
Mentions of these four paths can be found easily with control-F

Having show this, either the docs are wrong or the website is broken.
Thanks for fixing this bug.

**Comment by dexter-2** [comment] 2020-05-06 09:18
Not a bug.

These endpoints are all private endpoints which must be contacted with POST requests with JSON body. As such we have not provided `curl` examples in the docs for these endpoints.

**Comment by mathewdblewis** [comment] 2020-05-07 01:20
Thanks for clearing this up and sorry the missunderstanding

**Comment by dexter-2** [comment] 2020-05-07 08:42
No problem! Please close the issue if you feel it's resolved. Thanks!

**Closed** 2020-05-07 21:23 UTC
